- examples/EmotiBit_Example/EmotiBit_Example.ino
- Supports reading up to 12 different sets of WiFi credentials from SD
- Supports leaving one WiFi source and automatically reconnecting to another
> Multi WiFi

- EmotiBit.cpp
- examples/EmotiBit_Example/EmotiBit_Example.ino
- toggled the sendResetPacket to true on a switch credentials
> Multi WiFi Crash

- EmotiBit.cpp
- EmotiBit.h
- examples/EmotiBit_Example/EmotiBit_Example.ino
Beta branch has the code modified, to work on the Beta boards. 
MLX-compatibility adds support for the MLX thermopile.
Merging to create a consolidated code.
> Merging branch with MLX-compatibility into Beta branch

- EmotiBit.h
- examples/EmotiBit_Example/EmotiBit_Example.ino
Changes:
1. Changed the handling of LED set/reset based on the updated NCP library.
2. Changed the addDebugPacket() function to use enum class.
> EmotiBitBeta-fix-DebugTags

- EmotiBit.h
- examples/EmotiBit_Example/EmotiBit_Example.ino
1. Short button press changes the Wifi Modes
2. Adding Callbacks to be attached to short and long button press.
> Added suport for switching between different WiFi power modes. 

- EmotiBit.cpp
- EmotiBit.h
- examples/EmotiBit_Example/EmotiBit_Example.ino
1. Changed the refresh rate of thermopile
2. Changed LED brightness
> Emoti bit beta fix thermopile refreshrate

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitWiFi.cpp
- EmotiBitWiFi.h
- testing/EmotiBitWifiTest/EmotiBitWifiTest.ino
- Fixed button control of WiFi toggling (needs testing on working board)
- Fixed leaving and re-entering WiFi issue #67 
- Needs version bump concomitant with pr merge
- Compatible with ofxOscilloscope beta-refactor v1.0.0+
- ***NOTE*** that the TypeTag::PING has changed to "PN" in EmotiBit_XPlat_Utils. Both EmotiBit_FeatherWing and ofxOscilloscope must be built with the latest master to be compatible.
> Emoti bit wifi power test

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitCalibration.cpp
- EmotiBitCalibration.h
- examples/EmotiBit_Example/EmotiBit_Example.ino
- Added new files `EmotiBitCalibration` **.h** and **.cpp** files.
- Working GSR calibration
- Calibration value calculated by taking average of 1000 EDL values.
- The Calibration value is then transmitted over WiFi, which can then be grabbed from the dataLog.txt file generated by the oscilloscope.
> Beta refactor calibration files

- EmotiBit.cpp
- Fixed edaFeedbackAmpR off by factor of 1M
- Added conditional to avoid div by zero in EDA calculation
- Removed calibration code
- Compatible with ofxOscilloscope beta-refactor v1.0.0+
> Removed calibration commit from cpp

- EmotiBit.cpp
- Fixed control message truncation
- Compatible with ofxOscilloscope beta-refactor v1.0.0+
> Fixed control message truncation

- EmotiBit.cpp
- EmotiBit.h
Updated EDA constants with latest empirical data
> Eda constants update

- DoubleBufferFloat.cpp
- EmotiBit.cpp
- EmotiBit.h
- EmotiBitWiFi.cpp
- examples/EmotiBit_Example/EmotiBit_Example.ino
Adding changes from asap-ship-fixes into beta-refactor. 
- Fixed frequent crash issue by managing free Memory on board.
- Fixed button press issues on EmotiBit
- Melexis changed to STEP_MODE
- Added dummyToggleISR
- Reduced Buffer Size to 32
- Fixed Triangle wave debug
- Added Serial debug toolchain
**Test Configuration**:
- Code tested both, in normal mode and test mode.
- Works EmotiBit Beta HW
- Compatible with EmotiBit Oscilloscope v1.0.14
- Requires upgrade of the EmotiBit_MLX90632 [library](https://github.com/EmotiBit/EmotiBit_MLX90632/pull/3)
> Merging asap-ship-fixes into beta-refactor

- EmotiBit.cpp
- library.properties
Modified the DEBUG typetag to EMOTIBIT_DEBUG, to resolve build conflicts in Linux.
- [EmotiBit_XPlat_Utils](https://github.com/EmotiBit/EmotiBit_XPlat_Utils/pull/2)
> chnaged emotibit debug typeTag

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitVersionController.cpp
- EmotiBitVersionController.h
Reduced the Version Detection class to just "detect version".
- Moved the SD setup and reading/initialization to EmotiBit Setup
-  Moved emotiBit wifi class init back to emotiBit setup
> Simplifies the functionality of the DetectEmotiBItVersion class

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitVersionController.cpp
- EmotiBitVersionController.h
Added changes  requested in [Review 2](https://github.com/EmotiBit/EmotiBit_FeatherWing/pull/120#pullrequestreview-599137117)
- Changed the Structure of class `EmotiBitVersionController` to make accessing Pins/Conatsnts easier in emotibit.cpp
- Added support to call hibernate when version is not detected
- Moved serial statements to EmotiBit::setup() to better represent the functions of detectEmotiBitVersion()
> Fix version control structure

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitEda.cpp
- EmotiBitEda.h
- EmotiBitVersionController.cpp
- EmotiBitVersionController.h
- library.properties
- Needs the library [EmotiBit_ADS1x15 Library](https://github.com/EmotiBit/EmotiBit_ADS1X15)
- Needs latest pull from https://github.com/EmotiBit/EmotiBit_NCP5623/pull/2
- Needs latest pull from  https://github.com/EmotiBit/EmotiBit_XPlat_Utils/pull/5
> Adds support for ADS_1113 on EmotiBit

- EmotiBitWiFi.cpp
Tested on open and secure wifi network
> Connects to open wifi if pw is left empty

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitEda.cpp
- EmotiBitVersionController.cpp
- EmotiBitVersionController.h
- Adds SKU and Serial number to info.json file for every recording
- https://github.com/EmotiBit/EmotiBit_XPlat_Utils/pull/17
```
{
"info": {
"name": "EmotiBitData",
"type": "Multimodal",
"source_id": "EmotiBit FeatherWing",
"hardware_version": "V04a",
"sku": "EM",
"device_id": "EM-V4-0000010",
"feather_version": "Adafruit Feather M0 WiFi",
"firmware_version": "1.3.28",
"created_at": "2022-03-07_15-48-39-423377"
}
}
```
---------------------
```
Successfully read variant info from NVM
[NVM VARIANT INFO] HW version: V04a
[NVM VARIANT INFO] SKU version: MD
[NVM VARIANT INFO] EmotiBit Number: 2
[NVM VARIANT INFO] EmotiBit device ID: MD-V4-0000002
```
> Added serial number and sku number to config file

- EmotiBit.cpp
- EmotiBit.h
- Adds `BV` to the output stream.
- Streamlines batter level calulcation
> Added fixes to streamline battery read

- EmotiBit.cpp
- EmotiBit.h
- Data acquisition now uses timers for sampling data
> fixed sampling rate for esp. Now, readsensors is called by hw timer count

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitWiFi.cpp
- EmotiBit_stock_firmware/EmotiBit_stock_firmware.ino
- Moves data capture routine (ISR) onto core 1.
- ISR now hits at 150Hz, with core working on 160MHz
- Adds new tool to record max time spent in ISR by different sensors.
> Feat esp isr opt

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitEda.cpp
- EmotiBitVersionController.cpp
- EmotiBitVersionController.h
- EmotiBitWiFi.cpp
- EmotiBit_stock_firmware/EmotiBit_stock_firmware.ino
Cleaned up #ifdef to make code more maintainable and extensible
- closes #209
- Moved outstanding items to #225
> Feat fix esp if def

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitEda.cpp
- EmotiBitWiFi.cpp
- EmotiBitWiFi.h
- Working with Feather M0 WiFi & ESP32
- Reconnecting to WiFi on ESP32 can cause DO in some cases
- PR #(Link PR)
- Fixes #225 
- Fixes #229 
- Fixes #226 
- Fixes #213 
- Remaining issues moved to #231
> Feat esp leftovers

- EmotiBit.h
- EmotiBitEda.cpp
- library.properties
EDA values now limited to 10,000 uSiemens 
None
> Changed eda clamp from 1K to 100R

- EmotiBit.cpp
- EmotiBit.h
Stopped printing EmotiBit info in FACTORY_TEST mode
> Fix factory test serial info

- EmotiBit.h
- library.properties
- Fixes to improve Heart rate.
- All changes live in the linked PR.
- This PR only contains a version bump in the main FW repo.
- https://github.com/EmotiBit/EmotiBit_MAX30101/pull/10
- https://github.com/EmotiBit/EmotiBit_FeatherWing/issues/245
- None
- None
- Complete algorithm design and testing can be found in the `Heartbeat Det AC Filter Calculator` sheet
- Check `Heartbeat Det AC Filter Calculator` sheet
- Check the linked PR
- Firmware
> Fix improve hr

- README.md
Updated README.md to include library dependency version.
> Updated README.md to include library dependency version.

- CheckoutMasterEmotiBitFW.sh
- CloneEmotiBitFW.sh
- EmotiBit_FeatherWing_depends.txt
Fixes the scripts that clone/checkout master/pull from EmotiBit firmware repos
- This only handles EmotiBit owned repos
- In the future it may be even better to read from library.properties to avoid multiple source of truth
> Fixed shell scripts for repo management

- testing/GpioInterruptLogger/GpioInterruptLogger.ino
- testing/InterruptBasedGpioToggle/InterruptBasedGpioToggle.ino
- Adding example that allow event timestamping on external feather M0 using interrupts.
> Feat timing test tool

- EmotiBit.cpp
- EmotiBit.h
- FileTransferManager.cpp
- FileTransferManager.h
- README.md
- board_feather_esp32.ini
- library.properties
- Adds implementation for FTP server
- Adds FileTransferManager class
- New library: https://github.com/EmotiBit/EmotiBit_SimpleFTPServer
- https://github.com/EmotiBit/EmotiBit_SimpleFTPServer/pull/3
- None
- ToDo: Update documentation.
- Adding new dependency in the library list
- How to enter FTP mode
- It is important to setup FTP client on the computer as shown here: https://mischianti.org/simple-ftp-server-library-now-with-support-for-wio-terminal-and-sd/#Configure_client
- Synopsis of results, details if required.
- FTP server functionality on Feather M0 (verify serial out saying "not currently supported")
- FTP server functionality on ESP32
- FTP server does not start when recording
- FTP server example: EmotiBit-FileTransferManager
- Firmware binary: 
- …
> Adds FileTransferManager class
