EmotiBit/EmotiBit_FeatherWing

- EmotiBit.cpp
- examples/EmotiBit_Example/EmotiBit_Example.ino
- library.properties
- SD could cause system crash after RB (Record Begin) on certain FeatherWings, including CharliePlex, due to longer ISR times or greater resource consumption
- The ISR timer is now stopped at reception of RB and restarted after basic file management
- Tested on the CharliePlex, NeoPixel, and no additional FeatherWings
> Stopped the ISR for the initialization of SD during RB

- EmotiBit.cpp
- EmotiBit.h
- examples/EmotiBit_Example/EmotiBit_Example.ino
- Updates to hibernate()
- shut off power to GSR and thermistor
- put accelerometer, gyro, and magnetometer into suspend mode
- down to ~2.5mA draw (0.01 W) from possibly ~ 7-9 mA
- Includes the ~1mA contribution of the Feather M0
- Proper support for SD writing without WiFi connection
- Move some const definitions and added more #ifdefs
- Added autoSDwrite(), which should be called in setup()
- Should be used with ofxEmotiBit v0.6.0+
- Should be used with EmotiBit BMI160 v0.2.0+
> Hibernate and Recording

- EdaCorrection.cpp
- EdaCorrection.h
- EmotiBit.cpp
- EmotiBit.h
- EmotiBitVersionController.cpp
- EmotiBitVersionController.h
- examples/EmotiBit_Example/EmotiBit_Example.ino
- Adds `Autodetecting Emotibit Version` on startup. 
- The emotibit class no longer needs a version input from the user in code.
- Simply plug in Either version of emotibit(V2 or V3), and the feather can automatically detect and start working with the emotibit.
- The EmotiBit version is detected.
- The `EDR` pin is measured for different `hibernate pin` states, and this test is used to evaluate the emotibit version.
- `V2` activates EDR when the hibernate pin is LOW 
- `V3` activates EDR when the hibernate is HIGH
- Pin and constant assignments are stored in separate arrays `_assignedPin`, `_assignedMathConstant` and `_assignedSystemConstants`.
- These arrays are indexed using the enum classes `PinNames`, `MathConstants` and `SystemConstants`
- Using the getMapping function, the data …
> Feat emotibit cross version compatibility

- AdcCorrection.h
- EdaCorrection.cpp
- EdaCorrection.h
- EmotiBit.cpp
- EmotiBit.h
- EmotiBitVersionController.cpp
- EmotiBitVersionController.h
- Created new class `EmotiBitVersionDetection` enclosed in class `EmotiBitVersionController`
- This class handles detecting the version of the plugged emotibit to enable power up procedure and initiate I2c.
- After the I2C has been initiated, the class reads the version stored on the Si-7013 OTP. If No version is found, the emotibit continues with the estimate of the version detected.
- EmotiBit.cpp
- The following functions have been pulled out
- `detectEmotiBitVersion` - moved to class `EmotiBitVersionDetection`
- `setupSdCard` - moved to class `EmotiBitVersionDetection`
- `loadConfigFile`- moved to class `EmotiBitVersionDetection`
- EdaCorrection
- `readEmotiBitVersion` has been moved to `EmotiBitVersionDetection`
> Moved EmotiBit version detection outside EmotiBit.cpp

- AdcCorrection.cpp
- AdcCorrection.h
- EdaCorrection.h
- EmotiBit.cpp
- EmotiBit.h
- The Analog read function call returns values offset by a certain factor when called from within the ISR.
- The offset appears to be constant can be corrected after it has been measured.
- `AdcCorrection class`
- `updateIsrOffsetCorr` New function added to write the isr offset correction on to the at-winc flash
- `EmotiBit.cpp`
- new provision in setup to add isr correction offset.
- This provision works only if the adc correction has been initially applied
- `updateEDA`
- The recorded edl and edr value are now offset corrected before tx to the oscilloscope
- `EmotiBit.h `
- new testing mode added `ISR_CORRECTION_UPDATE`. 
- This new mode is required to send "raw adc values" of the edl and edr to the oscilloscope. 
- when in Eda calibration mode, this mode is automatically disabled …
> Adds an offset correction for Analog read called in the ISR sub routine

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitVersionController.cpp
- EmotiBitVersionController.h
- library.properties
- Adds support to be able to detect V4 EmotiBits
- V4 is detected by sending an ACK on the i2c line for the flash EEPROM
- The version detection has been changed from using the SD-Card to reading the Hibernate pin voltage on startup
- For V2, hibernate is pulled HIGH
- for V3 and V3+, hibernate is pulled LOW(internally by the LP5912 IC
- To differentiate between V3 and V3+, we query the presence of EEPROM.
> Feat version controller v4

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitVersionController.cpp
- EmotiBitVersionController.h
- Adds support to cross validate the Version and SKU from the barcode.
- Uses a new container `Barcode` to store barcode details in the setup.
- Changed the Setup output string to use MESSAGE_START and MESSAGE_TERM characters.
- No longer compatible with factory test SW 1.1.4 or lower
- Needs https://github.com/EmotiBit/EmotiBit_XPlat_Utils/pull/9
- If using the Factory test SW, Needs the latest https://github.com/connectedfuturelabs/EmotiBit_Factory_Test/pull/19 
- example barcodes: `MD-V3-123456`, `MD-V4-123456`
- Tested inputs
- ![image](https://user-images.githubusercontent.com/31810812/134415690-c6dc2500-937a-4a80-866c-ea09fbf89192.png)
- ![image](https://user-images.githubusercontent.com/31810812/134415895-3b001300-f5a7-4370-9ef8-41f766cb57ef.png)
> Added changes to support version and sku verification from barcode

- EmotiBit.cpp
- EmotiBit.h
- https://github.com/EmotiBit/EmotiBit_XPlat_Utils/pull/12
In FACTORY_TEST_MODE
- sending to EmotiBit `@S+,EL~` over serial toggles EL data to be sent over serial
- `@S-,EL~` stops serial sending 
- Someday we may want to refactor to centralize Serial.read() so that messages will work in FACTORY_TEST_MODE and normal mode. Right now it's a bit hard to have serial messages processed in multiple modes.
> Serial data can be toggled on/off for each DataType

- EmotiBit.cpp
- EmotiBit.h
- Barcode sent from testing software is now sent in a standard msg format.
- https://github.com/EmotiBit/EmotiBit_XPlat_Utils - v1.3.3+
> barcode is now received in std msg format

- EmotiBit.cpp
- EmotiBit.h
- EmotiBit_stock_firmware/EmotiBit_stock_firmware.ino
- Modification in Sleep(previously hibernate) protocol. The I2C pins are marked as `OUTPUT` `LOW` before sleeping with the `DRIVE STRENGTH` changed to `HIGH`
- refer[ #411](https://github.com/connectedfuturelabs/CFL_EE_BioSensor/issues/411) for details.
|EmotiBit Version| Sleep Current| SCL Voltage in Sleep| SDA voltage in Sleep|
|------------------|----------------|-----------------------|------------------------|
|V2 |0.5mA |10mV |10mV|
|V3 |0.5mA|10mV|10mV|
|V4 |7mA|0.1V |0.1V|
> Feat new Sleep protocol

- EmotiBit.cpp
- EmotiBit.h
- Adds a new data stream. EmotiBit now records the temperature from the bottom of EmotiBit using the MAX30101.
- The Temperature data is piped into typetag `T1`
- https://github.com/EmotiBit/EmotiBit_MAX30101/pull/4
- https://github.com/EmotiBit/EmotiBit_XPlat_Utils/pull/14
- Addition of sensor data to info.json
```  {
"info": {
"name": "Temperature EmotiBit Bottom",
"type": "Temperature",
"typeTags": [ "T1" ],
"channel_count": 1,
"nominal_srate": 7.5,
"channel_format": "float",
"units": "degrees celcius",
"sensor_part_number": "MAX30101",
"setup": {
"samples_averaged": 1,
"oversampling_rate": 7.5
}
}
},
```
- Oscilloscope streaming EM
- ![image](https://user-images.githubusercontent.com/31810812/150566737-f36e16e8-b384-426b-9030-09695293107c.png)
- Oscilloscope streaming MD
> Feat ppg temp

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitEda.cpp
- EmotiBitEda.h
- library.properties
- Adds `HR` and `EDR` derivatve metrics
- https://github.com/EmotiBit/EmotiBit_XPlat_Utils/pull/15
- to test: https://github.com/EmotiBit/ofxEmotiBit/pull/84
- #172 
- #173 
|Test | Process| Results|
|---|----|---|
|Test `addpacket()` functionality after change| Send `S+:Typetag~` over serial in factory test mode| PASS|
|Record| init record session | data recordign works and packet structure is maintained|
|Data Parser| Test by parsing recorded data| PASS. data parser successfully parser new data types|
|HR | view stream in oscilloscope| PASS. HR measured reasonably close to HR obtained using a oximeter|
|EDR Amplitude| view stream in oscilloscope | PASS. Amplitude detected in 100K, 1M, 10M|
|EDR Rise Time | view stream in oscilloscope  | PASS. Each EDR vent has an associated rise time| …
> Feat HR and EDR metrics

- EmotiBit.h
- EmotiBitEda.cpp
- Reduced the lowpass filter cutoff frequency for Skin Conductance response metrics
- SCR derivative metrics are more immune to noise and spurious changes.
- None
- https://github.com/EmotiBit/EmotiBit_FeatherWing/issues/181
- screen grabs for different filters attached in the issue
> Fix scr derivate sensitivity

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitEda.cpp
- Introduces new light up sequence for EmotiBit during bootup.
- please close #183 first
- https://github.com/EmotiBit/EmotiBit_FeatherWing/issues/184
- Feather RED LED glows up first. Stays on if SD-Card is detected, else turns OFF
- Only Feather RED LED stays on while sensors are being set up
- After sensor setup is complete, the EmotiBit RED LED turns on, indicating EmotiBit is scanning for config file.
- After config file is found EmotiBit RED turns off and EmotiBit BLUE turns on.
- After EmotiBit is connected to WIFI, Feather green light turns ON
- Replace `sleep` on no SD-Card to `while(1)`
> Features new LED light up sequence during bootup

- EmotiBit.h
- EmotiBitEda.cpp
- library.properties
Fixes an issue with false detection of SCR events
- fixes #188 
- Data was recorded with the fix implements. Only SCR events with Amplitude > 0 were recorded in the data.
- Also check out comments in #188 for verified false detections.
> Added fix to prevent false detection from being logged in data

- EmotiBit.h
- EmotiBitEda.cpp
- Fixes bug in SF sampling rate.
- `SF` was being recorded at 3x the events/min(mathematical error)
- Fixes #193 
Refer issues for test/results of the fixes applied.
> added bug fix to correct SF sampling rate to events/min

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitVersionController.cpp
Added a feature to detect LDO failures in the `SD-Card not detected` state by pressing the `EmotiBit Button`
- none
- Fixes #236 
none
Booting EmotiBit without SD card `SD-Card not detected` state. Pressing the button prints `Button Press Detected`.
> Feat detect LDO fail

- EmotiBit.cpp
- EmotiBit.h
- Added a bufferOverflowTest() to print buffer size, capacity, overflowCount periodically to assess DoubleBuffer time intervals.
- Adjusted buffer sizes to enable 2.40 seconds of buffering on M0
- Added BUFFER_SIZE_FACTOR = 2 for ESP32 to enable 4.80 seconds of buffering
- none
- none
- none
- In TestingMode::ACUTE enter 'o' in the serial monitor. Note the first totalDuration in which overflows are observed (third number after TypeTag. Note that some TypeTags are only updated in update() and thus do not increment.
|Test #| Feather | EmotiBit Version | Time for first overflow (mS) | console output |
|------|---------|--------------------|-------------------------------|-------------------|
| 1 |Feather M0 | v4 |  2370 | ![image](https://user-images.githubusercontent.com/31810812/202564479-f …
> Feat buffer limit test

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitVersionController.cpp
- EmotiBitVersionController.h
- Updated EmotiBitVersion, EmotiBitPinName, initPinMapping
- See `FW update instructions to support new HW version (EmotiBit).gdoc`
- none
- none
- none
- ✅  M0: v02 finishes setup
- ✅ M0: v03 finishes setup
- ✅ M0: v04 finishes setup
- ❌ ESP32: v02 fails setup (known issue)
- ✅ ESP32: v03 finishes setup
- ✅ ESP32: v04 finishes setup
- ✅ v05c barcode on v04 HW read in factory test
- ✅ streaming after factory test completed
**Test Configuration**:
* Firmware version:
* EmotiBit software version: v1.5.10
* EmotiBit Factory Test version: v1.3.5
- Make sure the required settings have been set to default before merging into master.
> Added EmotiBit HW version v05c support

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitVersionController.cpp
- library.properties
Fixes problem with EmotiBitFactoryTest::convertBarcodeToVariantInfo() by conforming to uppercase V prefix
none
none
none
Passes FactoryTest
- Make sure the required settings have been set to default before merging into master.
> Fixes version v05c to V05c

- examples/EmotiBit_examples/charlieplex_heartbeatOnSleeve/charlieplex_heartbeatOnSleeve.ino
- library.properties
- updated `library.properties` and fixed charlieplex example to use updated Emoji library name and location
- https://github.com/EmotiBit/EmotiBit_EmojiLib
- Fixes #186 
- https://github.com/EmotiBit/EmotiBit_Docs/pull/105#discussion_r1101994979
- Compiles ✔️ 
- Make sure the required settings have been set to default before merging into master.
> fixed charlie plex example to reflect updated location and name of EmotiBit Emojis

- EmotiBit.h
- EmotiBitWiFi.cpp
- library.properties
Fixes a bug where network switching on feather M0 would take [`attemptDelay`](https://github.com/EmotiBit/EmotiBit_FeatherWing/blob/2c7cc6fcbf87d8d04421964b404c9685f8882b59/EmotiBit.cpp#L951) (set in code) seconds. This artifact was introduced when changes were made to support enterprise wifi on ESP32.
This bug caused the Feather M0 to wait for 20 secs before switching networks (even if the network it was trying to connect to was not available).
This patch fixes that issue and now, if a network is not available (Feather M0 fails to connect to it), it moves on to the next network.
- None
- None
- None
The following shows the setup log indicating time taken between trying separate networks.
- Testing on ESP32 (**SSID not available**)
- Notice that even though the timeout is set to 20secs, …
> Added fix for long wait between connections on Adafruit feather m0

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitEda.cpp
- library.properties
Updating the ArduinoJson library to the latest version  and added free_memory() to display during bootup.
- ArduinoJson version 6
- Fixes #31 
Documentation should be changed under:
Keeping EmotiBit up-to date => Update firmware using Arduino IDE => Library List
where "ArduinoJson (version 5.13.5, not v6.x.x)" should be replaced with "ArduinoJson" since it is the latest version.
PR to documentation change.
- https://github.com/EmotiBit/EmotiBit_Docs/pull/113
- https://github.com/EmotiBit/EmotiBit_FeatherWing/pull/39 (Existing PR on upgrade)
The ArduinoJson Library must be updated to 6, the changes will not work with version 5. 
The free memory function was added to the function where emotibit data is displayed. This was only added in the case a featherwing m0 is used.
Test to make sure …
> Updated from ArduinoJson 5 to latest.

- EmotiBit.h
- EmotiBitEda.cpp
- Added nullptr checks. These were causing a crash on the agave board.
- None
- Fixes #293 
- None
- This is a minor patch, so there is no test added in the Feature test protocol doc.
- In the future, when we do implement a mechanism of "selectively setting up sensors", we will probably add a test to check that the fw does not crash if using a sensors module not setup
- For now, i just test it by bypassing eda setup in the `setup()`
```
// Setup EDA
#if(0) // #if defined out
{
Serial.println("\nInitializing EDA... ");
if (emotibitEda.setup(_hwVersion, _samplingRates.eda / ((float)_samplesAveraged.eda), &eda, &edl, &edr, _EmotiBit_i2c, &edlBuffer, &edrBuffer))
{
EmotiBitFactoryTest::updateOutputString(factoryTestSerialOutput, EmotiBitFactoryTest::TypeTag::ADC_INIT, …
```
> Added nullptr check in EmotibitEda_cpp

- EmotiBit.cpp
- EmotiBit.h
Changed `HR` precision from 0 to 2
#303
`HR` packets should have 2 decimal points
- [1.9.0.fix-hrPrecision.0.zip](https://github.com/EmotiBit/EmotiBit_FeatherWing/files/14749914/1.9.0.fix-hrPrecision.0.zip)
> Changed HR precision to 2

- EmotiBit.cpp
- EmotiBit.h
- EmotiBitLedController.cpp
- EmotiBitLedController.h
- EmotiBitVersionController.cpp
- EmotiBitVersionController.h
- testing/LedController/FactoryTestPrompt/platformio.ini
- testing/LedController/FactoryTestPrompt/src/main.cpp
- testing/LedController/LedController-testLedSequence/LedController-testLedSequence.code-workspace
- testing/LedController/LedController-testLedSequence/platformio.ini
- testing/LedController/LedController-testLedSequence/src/main.cpp
- Adds LED controller
- https://github.com/EmotiBit/EmotiBit_NCP5623/pull/4
- #309 
- Add detailed notes explaining code changes, algorithms or any other information that can help the reviewer understand the PR better.
- Led Controller Unit test (Feather ESP32)
- Flash the binary linked below (unit test) on a Feather ESP32. You may use the EmotiBit FirmwareInstaller to do so.
- plug in to serial monitor.
- reset feather
- Enter `6` into Serial input when prompted (set `No Line Ending` option). (This way you can start the example on a V5 and force the version to be V6 for testing the change of address for the IC)
- ![image](https://github.com/EmotiBit/EmotiBit_FeatherWing/assets/31810812/0255d18a-b27c-4f70-a2a7-d4bad646f008)
- **Notice the LED cycle through**.
- EmotiBit complete FW test
- …
> Feat led controller

- EmotiBit.cpp
- EmotiBit.h
- Moved `FileTransferManager` definitions to live under ESP board definitions. Since FTP is available only on ESP32, it does not affect Feather M0.
- This adds to the free memory available on the Feather M0, adding stability.
- None
- None
None
- Add detailed notes explaining code changes, algorithms or any other information that can help the reviewer understand the PR better.
- Name all new files added with this PR that need to be distributed with the release package. This includes files like `.json`, `.xml` settings files etc.
- ✔️ Repeated connect/disconnect
- ✔️ Repeated Record begin/record end tests
- Firmware binary: [Link to firmware binary]
- Other files.
- Firmware
> Increase available memory on the Feather M0
